### ISSUE TITLE
Nullable check does not work with GenericForeignKey field in Django datasource.

### ISSUE THREAD

**Issue by ditansu** [dry-python/mappers#183]
In current project tried update  a version from 0.1.dev f2ab777 to  1.0.1 and got error

```console
/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/bin/python3 /Users/di/WELPS/src/api/src/manage.py runserver 0.0.0.0:8000
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/di/WELPS/src/api/src/core/admin.py", line 13, in <module>
    from revenue_cat_stats.tasks import run_sync_user_subscriptions_task
  File "/Users/di/WELPS/src/api/src/revenue_cat_stats/tasks.py", line 10, in <module>
    from revenue_cat_stats.client import RevenueCatClient, RevenueCatClientNotFoundError
  File "/Users/di/WELPS/src/api/src/revenue_cat_stats/client/__init__.py", line 7, in <module>
    from newsfeed.helpers import str_to_datetime
  File "/Users/di/WELPS/src/api/src/newsfeed/helpers.py", line 9, in <module>
    from newsfeed.services.errors import NewsFeedServiceErrors
  File "/Users/di/WELPS/src/api/src/newsfeed/services/__init__.py", line 2, in <module>
    from newsfeed.services.simple_posts import SimplePostService
  File "/Users/di/WELPS/src/api/src/newsfeed/services/simple_posts.py", line 11, in <module>
from newsfeed.services.base import BaseDjangoRepoPostService
  File "/Users/di/WELPS/src/api/src/newsfeed/services/base.py", line 15, in <module>
    from newsfeed.repositories.utils import load_repo
  File "/Users/di/WELPS/src/api/src/newsfeed/repositories/__init__.py", line 1, in <module>
    from . import common
  File "/Users/di/WELPS/src/api/src/newsfeed/repositories/common.py", line 14, in <module>
    social_user_mapper = Mapper(
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/_mappers/factory.py", line 15, in mapper_factory
    iterable = _configure(entity, data_source, config)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/_mappers/factory.py", line 52, in _configure
    data_source_fields, data_source_factory = _data_source_factory(data_source)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/_mappers/sources/__init__.py", line 7, in _data_source_factory
    fields = django._get_fields(data_source)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/_mappers/sources/django.py", line 30, in _get_fields
    disassembled = _disassemble_field(field)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/_mappers/sources/django.py", line 51, in _disassemble_field
    disassembled["link_to"] = _get_fields(
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/_mappers/sources/django.py", line 30, in _get_fields
    disassembled = _disassemble_field(field)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/_mappers/sources/django.py", line 51, in _disassemble_field
    disassembled["link_to"] = _get_fields(
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/_mappers/sources/django.py", line 30, in _get_fields
    disassembled = _disassemble_field(field)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/_mappers/sources/django.py", line 51, in _disassemble_field
    disassembled["link_to"] = _get_fields(
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/_mappers/sources/django.py", line 30, in _get_fields
    disassembled = _disassemble_field(field)
  File "/Users/di/Library/Caches/pypoetry/virtualenvs/api-g4jWUIfB-py3.8/lib/python3.8/site-packages/_mappers/sources/django.py", line 45, in _disassemble_field
    "is_nullable": bool(field.null),
AttributeError: 'GenericForeignKey' object has no attribute 'null
```
source code

```python
from uuid import UUID
from typing import List

from mappers import Mapper, Evaluated

from django.db.models import Subquery
from django.contrib.auth import get_user_model

from newsfeed.models.common import Influencer, SocialSubscription
from newsfeed.aggregates.user import SocialUserEntity

UserModel = get_user_model()

social_user_mapper = Mapper(
    SocialUserEntity, UserModel,
    {
        'primary_key': 'pk',
        'id': Evaluated(),
    }
)

influencer_mapper = Mapper(
    SocialUserEntity, Influencer,
    {
        'id': Evaluated('user__pk'),
        'name': Evaluated('user__name'),
        'photo': Evaluated('user__photo'),
        'sex': Evaluated('user__sex'),
    }
)


@social_user_mapper.reader
def load_users_by_ids(users_ids: List[UUID]) -> List[SocialUserEntity]:
    users = UserModel.objects
    users = users.filter(pk__in=users_ids)
    users = users.only('id', 'name', 'photo', 'sex')
    return users


@social_user_mapper.reader
def load_influencers(current_user_id: UUID = None) -> List[SocialUserEntity]:
    # load all influencers
    if current_user_id is None:
        return UserModel.objects.filter(influencer__isnull=False)

    # load user subscription influencers
    subscriptions = SocialSubscription.objects.filter(subscriber_id=current_user_id)
    users = UserModel.objects
    users = users.filter(pk__in=Subquery(subscriptions.values('publisher')))
    return users
```

**Comment by proofit404** [comment]
@ditansu thanks for the report.

Could you provide the definition of the `SocialUserEntity` entity, `UserModel` and `Influencer` models?

**Comment by ditansu** [comment]
@proofit404  sure

**`SocialUserEntity`**

```python
from dataclasses import field

from django.conf import settings
from pydantic.dataclasses import dataclass as pydantic_dataclass
from typing import List, Dict, Optional
from uuid import UUID

from core.choices import SexChoice


@pydantic_dataclass
class SocialUserEntity:
    id: UUID
    publisher_id: UUID
    subscriber_id: UUID
....
```

**`UserModel  ==  WelpsUser == AUTH_USER_MODEL`**

```python
import uuid

from django_extensions.db.fields.json import JSONField

from django.db import models
from django.conf import settings
from django.db.models import Index
from django.contrib.auth.models import Group, Permission, AbstractBaseUser
from django.db.models.fields.files import ImageFieldFile
from django.contrib.postgres.fields import JSONField as PostgresJSONField
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from core.mixins import SignalLogMixin, PermissionsMixin
from core.choices import SexChoice, GoalChoice, UnitChoice, WelpsSettingsChoices, WelpsSettingsTypeChoices
from core.helpers import get_file_extension
from core.managers import WelpsUserManager
from core.model_fields import CustomDateField, CustomDateTimeField
from trainings.choices import LevelChoice, ProgramType
from core.storage_utils import get_media_storage


def photo_dir_path(instance, filename=None):
    file_extension = get_file_extension(filename)
    file_name = f'{str(uuid.uuid4())}.{file_extension}'
    return f'user/{instance.pk}/avatar/{file_name}'


class Log(models.Model):
    content_type = models.ForeignKey(ContentType, null=True, on_delete=models.SET_NULL)
    object_id = models.CharField(max_length=128, null=False, blank=False, db_index=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    date = CustomDateTimeField('Date')
    object_data = JSONField('Object Data', default={}, blank=True)

    class Meta:
        db_table = 'welps_core_log'
        verbose_name_plural = 'Logs'
        indexes = [
            Index(fields=['object_id', 'content_type'], name='core_log__obj_id__con_type')
        ]

    def __str__(self):
        return f'id={self.id}, obj_id={self.object_id}'

    @classmethod
    def create(cls, obj, date, object_data):
        obj = cls.objects.create(
            content_type=ContentType.objects.get_for_model(obj),
            object_id=obj.pk,
            date=date,
            object_data=object_data,
        )
        return obj

    @classmethod
    def get_for_object(cls, obj):
        return cls.objects.filter(
            content_type=ContentType.objects.get_for_model(obj),
            object_id=obj.pk
        ).order_by('date', 'pk')


class WelpsUserBase(SignalLogMixin, PermissionsMixin, AbstractBaseUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='ID')
    created_at = CustomDateTimeField(null=True, auto_now_add=True, verbose_name='дата создания')
    updated_at = CustomDateTimeField(null=True, auto_now=True, verbose_name='дата обновления')
    username = models.CharField(unique=True, max_length=255, verbose_name='логин')
    phone = models.TextField(null=True, blank=True, unique=True, verbose_name='телефон')
    email = models.EmailField(null=True, blank=True, unique=True, verbose_name='почта')
    is_staff = models.BooleanField(default=False, verbose_name='есть доступ в админку?')
    is_superuser = models.BooleanField(default=False, verbose_name='суперадмин?')
    groups = models.ManyToManyField(blank=True, to=Group, verbose_name='группы')
    user_permissions = models.ManyToManyField(blank=True, to=Permission, verbose_name='права')
    is_deleted = models.BooleanField(default=False, blank=True)
    on_delete_comment = models.TextField(default='', blank=True)
    soft_delete_data = PostgresJSONField(default=dict, blank=True)

    is_test_user = models.BooleanField(default=False)

    objects = WelpsUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    class Meta:
        abstract = True
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        db_table = 'welps_core_user'
        swappable = 'AUTH_USER_MODEL'
        ordering = ['-created_at', ]
        indexes = [
            models.Index(fields=['created_at']),
        ]

    def save(self, *args, **kwargs):
        if not self.email:
            self.email = None
        if not self.phone:
            self.phone = None
        super().save(*args, **kwargs)

    def __str__(self):
        return f'ID: {self.pk}, phone: {self.phone}'


class WelpsUser(WelpsUserBase):
    LOG_ENABLED = True
    LOG_FIELDS = [
        'phone',
        'email',
        'username',
        'date_of_birth',
        'sex',
        'weight',
        'height',
        'tested',
        'level',
        'goal',
        'profiled',
        'is_deleted',
    ]
    SIGNAL_ENABLED = True
    SIGNAL_FIELDS = LOG_FIELDS

    name = models.TextField(null=True, blank=True, max_length=64, verbose_name='имя')
    surname = models.TextField(null=True, blank=True, max_length=150, verbose_name='фамилия')
    locale = models.TextField(default='', blank=True)
    timezone = models.TextField(default='', blank=True)
    date_of_birth = CustomDateField(null=True, blank=True, verbose_name='день рождения')
    sex = models.CharField(null=True, blank=True, max_length=32, choices=SexChoice, verbose_name='пол')
    photo = models.ImageField(
        null=True,
        blank=True,
        upload_to=photo_dir_path,
        storage=get_media_storage(),
        max_length=512,
        verbose_name='фото',
    )
    units = models.CharField(
        choices=UnitChoice, max_length=32, default=UnitChoice.METRIC,
        null=False, blank=True, verbose_name='система измерений',
    )
    about = models.TextField(null=True, blank=True, verbose_name='о себе')
    weight = models.FloatField(null=True, blank=True, verbose_name='вес')
    goal_weight = models.FloatField(null=True, blank=True, verbose_name='желаемый вес')
    height = models.FloatField(null=True, blank=True, verbose_name='рост')

    tested = models.BooleanField(
        null=False, blank=False, verbose_name='прошёл ли пользователь фитнес тестирование', default=False,
    )

    profiled = models.BooleanField(
        null=True, blank=True, verbose_name='прошёл ли пользователь профилирование', default=None,
    )

    level = models.CharField(
        choices=LevelChoice, max_length=32, blank=True, null=False,
        verbose_name='уровень тренировок'
    )

    goal = models.CharField(
        null=True,
        blank=True,
        choices=GoalChoice,
        max_length=32,
        verbose_name='цель',
    )

    program_type = models.CharField(
        null=True,
        blank=True,
        choices=ProgramType,
        default=ProgramType.HOME,
        max_length=32,
        verbose_name='Тип тренировок'
    )

    show_gym = models.BooleanField(default=True, verbose_name='показывать призыв идти в зал в плане?')

    freshchat_restore_id = models.UUIDField(null=True, blank=True, unique=True)

    @property
    def actual_photo(self):
        # I see no photo for deleted user
        if self.is_deleted is True:
            # Return an empty image object not None value
            return ImageFieldFile(instance=self, field=self.photo, name=None)
        return self.photo

    def get_user_test_result(self):
        return self.userfitnesstest_set.all()

    def get_user_test_result_count(self):
        return self.userfitnesstest_set.count()


class WelpsUserMeta(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key=True, on_delete=models.CASCADE,
                                related_name='meta', verbose_name='пользователь')
    app_build = models.TextField(null=True, blank=True, verbose_name='сборка аппа')
    app_version = models.TextField(null=True, blank=True, verbose_name='версия аппа')
    device = models.TextField(null=True, blank=True, verbose_name='девайс')
    locale = models.TextField(null=True, blank=True, verbose_name='локаль')
    os = models.TextField(null=True, blank=True, verbose_name='ОС')
    platform = models.TextField(null=True, blank=True, verbose_name='платформа')
    timezone = models.TextField(null=True, blank=True, verbose_name='таймзона')

    class Meta:
        db_table = 'welps_core_user_meta'
        verbose_name = 'User Meta'
        verbose_name_plural = 'User Meta'


class WelpsSettings(models.Model):
    DEFAULTS = {
        WelpsSettingsChoices.FITNESS_TEST_DURATION: (WelpsSettingsTypeChoices.NUMBER, '900'),
        WelpsSettingsChoices.FITNESS_TEST_TITLE: (WelpsSettingsTypeChoices.STR, 'Фитнес тестирование'),
        WelpsSettingsChoices.FITNESS_TEST_IMAGE_URL: (
            WelpsSettingsTypeChoices.STR,
            getattr(settings, 'FITNESS_TEST_IMAGE_URL', 'https://change_FITNESS_TEST_IMAGE_URL.var')),
        WelpsSettingsChoices.ONE_EXERCISE_DURATION: (WelpsSettingsTypeChoices.NUMBER, '3'),
        WelpsSettingsChoices.ERROR_TRAINING_DURATION: (WelpsSettingsTypeChoices.NUMBER, '900'),
        WelpsSettingsChoices.ERROR_TRAINING_TITLE: (WelpsSettingsTypeChoices.STR, 'ТРЕНИРОВКИ В ЗАЛЕ НЕ ПОДДЕРЖИВАЮТСЯ'),
        WelpsSettingsChoices.ERROR_TRAINING_BLOCK_TITLE: (WelpsSettingsTypeChoices.STR,
                                                          'Тренировки в зале не поддерживаются в вашей версии приложения'),
        WelpsSettingsChoices.ERROR_TRAINING_IMAGE_URL: (
            WelpsSettingsTypeChoices.STR,
            getattr(settings, 'ERROR_TRAINING_IMAGE_URL', 'https://change_ERROR_TRAINING_IMAGE_URL.var')),
    }

    CONVERTERS = {
        WelpsSettingsTypeChoices.NUMBER: float,
        WelpsSettingsTypeChoices.STR: lambda x: x
    }

    welps_settings_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='ID')
    key = models.CharField(null=False, blank=False, unique=True, choices=WelpsSettingsChoices, max_length=50,
                           verbose_name='название переменной')
    value = models.CharField(null=False, blank=False, max_length=1000, verbose_name='значение')
    type = models.CharField(null=False, blank=False, choices=WelpsSettingsTypeChoices, max_length=20,
                            verbose_name='тип переменной')
    created_at = CustomDateTimeField(null=True, auto_now_add=True, verbose_name='дата создания')
    updated_at = CustomDateTimeField(null=True, auto_now=True, verbose_name='дата обновления')

    @classmethod
    def get_value(cls, key):
        if key in cls.DEFAULTS:
            default = cls.DEFAULTS[key]
            ent = cls.objects.get_or_create(key=key, defaults={'type': default[0], 'value': default[1]})[0]
        else:
            try:
                ent = cls.objects.get(key=key)
            except cls.DoesNotExist:
                ent = None

        if ent is None:
            return None

        return cls.CONVERTERS[ent.type](ent.value)

    class Meta:
        verbose_name = 'переменная окружения'
        verbose_name_plural = 'переменные окружения'
        db_table = 'welps_core_settings'
        indexes = [
            models.Index(fields=['key']),
        ]
```

**`Influencer`**

```
class Influencer(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = CustomDateTimeField(null=True, auto_now_add=True)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='influencer', null=True, on_delete=models.SET_NULL,
    )

    class Meta:
        db_table = 'welps_news_feed_influencer'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['created_at']),
        ]

    def __str__(self):
        return f'{self.user_id}'
```
